SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
CASE
	WHEN PRECO_DE_LISTA >= 20 THEN 'PRODUTO MUITO CARO'
    WHEN PRECO_DE_LISTA >= 12 AND PRECO_DE_LISTA < 20 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO NA MEDIA'
    ELSE 'PRODUTO BARATO' END AS STATUS_PRECO FROM tabela_de_produtos;