


/*USANDO LIKE
BUSCA PELA CONTEUDO DA STRING INFORMADA, E O % É UMA MARCAÇÃO ESPECIAL INFORMANDO ONDE 
NO TEXTO VOCÊ QUER ACHAR ELE 
%TEXTO% -> PODE SER EM QUALQUER LUGAR DO TEXTO
%TEXT -> É ONDE CONTEM SOMENTE AO FINAL DO TEXT, EXEMPLO DE UM NOME LIKE '%A' -- SOMENTE NOMES QUE TERMINAM COM A
TEXT% -> AO CONTRARIO DO DE CIMA, NOME LIKE 'A%' NOMES QUE COMEÇAM COM A.
*/
SELECT * FROM tabela_de_clientes WHERE NOME LIKE 'A%'

/*DISTINCT 
NA EXIBIÇÃO NÃO MOSTRA SEQUENCIA REPITIDAS, OU SEJA NESSE EXEMPLO DE CIDADE = 'RIO DE JANEIRO' USANDO
O DISTINCT ELE NÃO VAI MOSTRAR BAIRROS REPITIDOS.
*/
SELECT DISTINCT BAIRRO FROM tabela_de_clientes WHERE CIDADE = 'Rio de Janeiro'

/*OUTRO EXEMPLO COM DISTINCT
NESSE CASO SEJA MAIS FÁCIL ENTENDER, VAI RETORNAR SOMENTE UM TIPO DE EMBALAGEM QUE POSSUI AQUELE TAMANHO
POR QUE O DISTINCT NÃO DEIXA REPITIR NA EXIBIÇÃO EX: SE TIVER DOIS PRODUTOS QUE SÃO EMBALAGEM PET E 2L SÓ APARECE 1 RESULTADO
*/
SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

/*
Garrafa	700 ml
PET	1 Litro
PET	1,5 Litros
PET	2 Litros
Lata	350 ml
Garrafa	470 ml
*/